### ISSUE TITLE
cannot clone this prj?

### ISSUE THREAD

**Issue by andyyuan78** [parry2403/R2N2#1]
envy@ub1404envy:/media/envy/data1t/github$ git clone https://github.com/parry2403/R2N2.git
Cloning into 'R2N2'...
remote: Counting objects: 84, done.
Unpacking objects:  67% (57/84)   

error: RPC failed; result=56, HTTP code = 200
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: unpack-objects failed
envy@ub1404envy:/media/envy/data1t/github$ 

I can clone other porject on github!

**Comment by parry2403** [comment]
Are you still facing the issue ?

**Comment by andyyuan78** [comment]
it works now
